package com.learn.interviewmentor.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * One student buying one plan.
 *
 * Deliberately its own entity rather than a reuse of {@link Payment}: that one
 * is @OneToOne against an InterviewRequest, so bending it to also mean "a plan"
 * would make both halves nullable and every query ambiguous. Two small tables
 * beat one table with two personalities.
 *
 * {@link #pricePaid} is a copy, not a lookup. An admin raising the price of the
 * Placement Guide must not retroactively change what somebody paid last month -
 * that is the whole reason this column exists.
 */
@Entity
@Table(name = "plan_enrollments")
public class PlanEnrollment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "plan_id", nullable = false)
    private Plan plan;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "student_id", nullable = false)
    private User student;

    /** What this student was actually charged, frozen at purchase time. */
    @Column(name = "price_paid", nullable = false, precision = 10, scale = 2)
    private BigDecimal pricePaid;

    /** Copied too, so a later change to the plan can't shorten existing access. */
    @Column(name = "duration_days", nullable = false)
    private int durationDays;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private EnrollmentStatus status = EnrollmentStatus.AWAITING_PAYMENT;

    @Column(name = "upi_reference", length = 40)
    private String upiReference;

    /** Filename on disk - generated by us, never the browser's. */
    @Column(name = "screenshot_file")
    private String screenshotFile;

    @Column(name = "screenshot_content_type", length = 60)
    private String screenshotContentType;

    @Column(name = "rejection_reason", length = 500)
    private String rejectionReason;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "submitted_at")
    private LocalDateTime submittedAt;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewed_by")
    private User reviewedBy;

    @Column(name = "activated_at")
    private LocalDateTime activatedAt;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    protected PlanEnrollment() {
        // JPA
    }

    public PlanEnrollment(Plan plan, User student) {
        this.plan = plan;
        this.student = student;
        this.pricePaid = plan.getPrice();
        this.durationDays = plan.getDurationDays();
        this.status = EnrollmentStatus.AWAITING_PAYMENT;
    }

    @PrePersist
    void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    /** Student sends proof. Also the resubmit path after a rejection. */
    public void submitProof(String upiReference, String screenshotFile, String contentType) {
        this.upiReference = upiReference;
        this.screenshotFile = screenshotFile;
        this.screenshotContentType = contentType;
        this.status = EnrollmentStatus.SUBMITTED;
        this.rejectionReason = null;
        this.submittedAt = LocalDateTime.now();
        this.reviewedAt = null;
        this.reviewedBy = null;
    }

    /** Admin confirmed the money arrived. This is what starts the clock. */
    public void activate(User admin) {
        this.status = EnrollmentStatus.ACTIVE;
        this.rejectionReason = null;
        this.reviewedAt = LocalDateTime.now();
        this.reviewedBy = admin;
        this.activatedAt = this.reviewedAt;
        this.expiresAt = this.activatedAt.plusDays(durationDays);
    }

    public void reject(User admin, String reason) {
        this.status = EnrollmentStatus.REJECTED;
        this.rejectionReason = reason;
        this.reviewedAt = LocalDateTime.now();
        this.reviewedBy = admin;
    }

    public void cancel() {
        this.status = EnrollmentStatus.CANCELLED;
    }

    /**
     * ACTIVE and still inside its window.
     *
     * The status column can lag reality - nothing sweeps the table at midnight -
     * so the date is checked here rather than trusted from the column alone.
     */
    public boolean isCurrentlyActive() {
        return status == EnrollmentStatus.ACTIVE
                && (expiresAt == null || expiresAt.isAfter(LocalDateTime.now()));
    }

    public boolean isOwnedBy(User user) {
        return student != null && user != null && student.getId().equals(user.getId());
    }

    public Long getId() { return id; }
    public Plan getPlan() { return plan; }
    public User getStudent() { return student; }
    public BigDecimal getPricePaid() { return pricePaid; }
    public int getDurationDays() { return durationDays; }
    public EnrollmentStatus getStatus() { return status; }
    public String getUpiReference() { return upiReference; }
    public String getScreenshotFile() { return screenshotFile; }
    public String getScreenshotContentType() { return screenshotContentType; }
    public String getRejectionReason() { return rejectionReason; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getSubmittedAt() { return submittedAt; }
    public LocalDateTime getReviewedAt() { return reviewedAt; }
    public User getReviewedBy() { return reviewedBy; }
    public LocalDateTime getActivatedAt() { return activatedAt; }
    public LocalDateTime getExpiresAt() { return expiresAt; }
}
